baseurl = "http://codaproductions.co.uk/"
title = "Coda Productions"
languageCode = "en-gb"
PluralizeListTitles=false
canonifyurls = false

[params]
    author = "Harry Bridge"
    email = "info@codaproductions.co.uk"
